stages:
  - build-test

image: node:16.5.0

build:
  stage: build-test
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - node_modules/
  script:
    - echo "RUNNING BUILD..."
    - npm i
    - npm run build
  rules:
    - if: $CI_COMMIT_BRANCH != "main"
