name: Workflow Change
description: We should change our workflow.
title: ⚠️ Insert a short title for your proposal.
labels: ["workflow"]
assignees: ["calejvaldez"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Summarize the proposed change concisely.
    validations:
      required: true
  - type: textarea
    id: reasoning
    attributes:
      label: Reasoning
      description: Why should we change our workflow? What's wrong with the current structure?
    validations:
      required: true
